version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  reviewers:
  - wojsmol
  - zwiastunsw
  allow:
  - dependency-type: direct
  - dependency-type: indirect
