repository: lepszyweb/wcag-testy

output: web
# Ta właściwość jest przydatna do warunkowego filtrowania zawartości, która jest oddzielona od pliku PDF.

topnav_title: Ocenianie dostępności cyfrowej
# pojawia się na górnym pasku nawigacji obok przycisku "Start".

site_title: Ocenianie dostępności cyfrowejxx
# pojawia się to w zakładce przeglądarki html dla tytułu strony (widzianej głównie przez wyszukiwarki, a nie przez użytkowników)

company_name: Pracownia Dostępności Cyfrowej LepszyWeb.pl
# pojawia się w stopce, może być użyte w instrukcjach warunkowych

github_editme_path: lepszyweb/wcag-testy/blob/gh-pages/

# Jeśli używasz Githuba, podaj ścieżkę basepath do utworzonej gałęzi do recenzji, zgodnie z przykładem powyżej. Jeśli nie, zostaw tę wartość pustą.

# gitlab_editme_path: tomjoht/documentation-theme-jekyll/blob/gh-pages/
# Jeśli używasz GitLaba, podaj ścieżkę bazową do utworzonej przez siebie gałęzi do recenzji, zgodnie z przykładem powyżej. Jeśli nie, zostaw tę wartość pustą.

google_analytics: UA-150239157-1
# Jeśli masz identyfikator google-analytics, wpisz go. Jeśli nie, zmień tę wartość na pustą.

host: 127.0.0.1
# używany serwer podglądu. Zostaw tak jak jest.

port: 4006
# port, na którym odbywa się podgląd. Możesz zostawić ten port tak jak jest, chyba że masz inne konstrukcje Jekyll'a używające tego samego portu, które mogą powodować konflikty. w takim przypadku użyj innego portu, np. 4006.

exclude:
  - .idea/
  - .gitignore
  - vendor
# to są te pliki i katalogi, które jekyll wykluczy z budowy

# feedback_subject_line: Temat wiadomości zwrotnej od użytkowników, jeśli włączone wysyłanie poczty e-email

# feedback_email: kontakt@lepszyweb.pl
# używany jako email kontaktowy dla linku Feedback na górnym pasku nawigacyjnym

# feedback_disable: true
# if you uncomment the previous line, the Feedback link gets removed
# jeśli odznaczysz poprzednią linię, link Feedback zostanie usunięty.

# feedback_text: "Potrzebujesz pomocy?"
# jeśli odkomentujesz poprzedni wiersz, zmieni się tekst  łącza Feedback

# feedback_link: "http://helpy.io/"
# if you uncomment the previous line, it changes where the feedback link points to
# jeśli odkomentujesz poprzednią linię, zmieni ona lokalizację, na którą wskazuje łącze Feedback

highlighter: rouge
# biblioteka służąca do podświetlania składni

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

# filtr używany do przetwarzania markdown. należy pamiętać, że kramdown różni się od markdown o smaku githuba pod pewnymi subtelnymi względami

collections:
  tooltips:
    output: false
# Tutaj dekalrowane są kolekcje (collections). To sprawia, że treść w _tooltips jest przetwarzana, ale nie jest wyświetlana jako rzeczywiste pliki na wyjściu, chyba że zmienisz wyjście na true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: false
      # jeśli nie chcesz używać Commento.io i po prostu ukryć komentarze, zmień true na false gdziekolwiek widzisz właściwość komentarzy
      search: true
      sidebar: home_sidebar
      topnav: topnav
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      search: true
      tooltip: true

  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      # jeśli nie chcesz używać Commento.io i po prostu ukryć komentarze, zmień true na false gdziekolwiek widzisz właściwość komentarzy
      search: true
      sidebar: home_sidebar
      topnav: topnav

# są to wartości domyślne używane dla nagłówków (frontmatter) dla tych typów plików

sidebars:
- home_sidebar
- metoda_sidebar
- standardy_sidebar
- testy-adept_sidebar
- testy-itc_sidebar
- testy-msu_sidebar
- testy-jbt_sidebar
- testy-proste_sidebar
- narzedzia_sidebar

description: "Celem projektu jest zbudowanie bazy wiedzy o dostępności cyfrowej stron internetowych i aplikacji mobilnych, aby pomóc wydawcom, koordynatorom dostępności cyfrowej, programistom, webmasterom, audytorom, testerom.

"
# opis ten jest stosowany w pliku feed.xml

# potrzebne tylko do pliku sitemap.xml
# url: http://idratherbewriting.com
# baseurl: /documentation-theme-jekyll


github: [metadata]
