#!/bin/sh

# Using a 'cat' here document, create a file for jekyll
# website containing what's required for tag pages.

# Pass in tag name(s)
#   ./createtag linux bsd

CMDLINEPARAM=1     #  Takes at least one param.
TAGDIR="pages/tags"

if [ $# -ge $CMDLINEPARAM ]
then
  tags=$@
else
  echo "Ostatnia nazwa taga ${CMDLINEPARAM} jest wymagana."
  exit 1
fi

if [ -d "${TAGDIR}" ]; then

  echo "Tworzenie tagu(-ów) dla ${tags}"

  for tag in ${tags}; do
    echo "Tytuł dla $tag:"
    read title
  # Cannot indent here string.
cat <<EOF >"${TAGDIR}/tag_${tag}.md"
---
title: "${title}"
tagName: ${tag}
search: exclude
permalink: tag_${tag}.html
sidebar: mydoc_sidebar
hide_sidebar: true
folder: tags
---

{% include taglogic.html %}

{% include links.html %}
EOF

echo "  - ${tag}" >> _data/tags.yml

  done

else
  echo "Folder ${TAGDIR} nie istnieje lub nie znajdujesz się w katalogu najwyższego poziomu."
  echo "Proszę, rozpocznij ponownie z głównego katalogu swojego projektu."
  exit 1
fi

exit
