backend:
  name: github
  repo: lepszyweb/wcag-testy  # your GitHub username and repository name, separated by a slash
  branch: gh-pages # optional, default value is "master"
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }
